### ISSUE TITLE
[DOCS] Broken links to Schema, Model, Collection

### ISSUE THREAD

**Issue by belgoros** [miragejs/ember-cli-mirage#1840]
The documentation page about [relationships](https://www.ember-cli-mirage.com/docs/data-layer/relationships) has some broken links in the very bottom of the page:

<img width="717" alt="Screenshot 2019-12-04 at 15 51 37" src="https://user-images.githubusercontent.com/83579/70152869-3d7dda00-16ae-11ea-9468-2148ca8609ef.png">

and raise the error in the browser console:
```
vendor-fabb0d88736848cb7d044447970ea191.js:3114 Error while processing route: docs.api.item Cannot read property 'get' of null TypeError: Cannot read property 'get' of null
    at r.model (https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:8028:5)
    at r.s.deserialize (https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:2982:131)
    at t.getModel (https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:5318:26)
    at https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:5298:222
    at E (https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:5480:12)
    at _ (https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:5478:128)
    at t.invoke (https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:5012:163)
    at e.t.flush (https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:5004:74)
    at e.t.flush (https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:5018:207)
    at e.r._end (https://www.ember-cli-mirage.com/assets/vendor-fabb0d88736848cb7d044447970ea191.js:5081:9)
```

**Comment by samselikoff** [comment]
https://github.com/miragejs/ember-cli-mirage/pull/1854 fixes
