### ISSUE TITLE
Unable to run the Docs dummy application after cloning repo

### ISSUE THREAD

**Issue by cah-briangantzler** [miragejs/ember-cli-mirage#2000]
after cloning the repo, running yarn, then ember s, when I navigate to localhost:4200 I get the following stacktrace.   I see that it is running via fastboot which I have yet to use. Is there perhaps something that I need to do on my machine in that respect?

```
App is being served by FastBoot
Error: Could not find module `fetch` imported from `dummy/instance-initializers/setup-fetch`
    at missingModule (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:247:1)
    at findModule (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:258:1)
    at Module.findDeps (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:168:1)
    at findModule (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:262:1)
    at requireModule (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:24:1)
    at r (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:176:1)
    at resolveInitializer (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/addon-tree-output/ember-load-initializers/index.js:10:1)
    at registerInstanceInitializers (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/addon-tree-output/ember-load-initializers/index.js:33:1)
    at loadInitializers (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/addon-tree-output/ember-load-initializers/index.js:69:1)
    at Module.callback (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/dummy/app.js:13:1)
    at Module.exports (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:104:1)
    at Object.requireModule (/Users/brian.gantzler/source-personal/ember-cli-mirage/tmp/broccoli_persistent_filtersimple_replace-output_path-ORBvJeuJ.tmp/assets/vendor/loader/loader.js:27:1)
    at Object.<anonymous> (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:213:18)
    at VMSandbox.run (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/ember-cli-fastboot/node_modules/fastboot/src/vm-sandbox.js:18:15)
    at EmberApp.createEmberApp (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:212:30)
    at EmberApp.retrieveSandboxedApp (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:237:17)
    at new EmberApp (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/ember-cli-fastboot/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/ember-cli-fastboot/node_modules/fastboot/src/index.js:52:10)
    at /Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/ember-cli-fastboot/index.js:335:29
    at Layer.handle [as handle_request] (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/express/lib/router/index.js:317:13)
    at /Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/express/lib/router/index.js:275:10)
    at /Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11
    at watcher.then.errorHandler.buildError (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatcher (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/rsvp/dist/lib/rsvp/-internal.js:39:19)
    at invokeCallback (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:31)
    at /Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/Users/brian.gantzler/source-personal/ember-cli-mirage/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)


```

**Comment by samselikoff** [comment]
Sorry for the delay!

You can disable Fastboot with the `FASTBOOT_DISABLED` ENV var:

```sh
FASTBOOT_DISABLED=true ember s
```

However, you shouldn't need to do this – the only reason we have `ember-cli-fastboot` installed is to make it available to some of the test projects. The main dummy app (which is the docs site) is never served via FastBoot.

So, we should just blacklist it for the dummy app so it doesn't affect it. I'll open a PR.

Thanks for opening this!

**Comment by cah-briangantzler** [comment]
I can confirm that following the above instructions does allow the docs to run.

Thanks

**Comment by samselikoff** [comment]
https://github.com/miragejs/ember-cli-mirage/pull/2004 closes
