### ISSUE TITLE
get "Unexpected token function" error when installing ember-cli-mirage

### ISSUE THREAD

**Issue by dinager** [miragejs/ember-cli-mirage#2125]
I am installing the ember-cli-mirage
 `ember install ember-cli-mirage`
node version: v6.17.1
I get this error:
```
Installed packages for tooling via npm.
Unexpected token function
/Users/dsolomon/Documents/learn-ember/super-rentals/node_modules/@embroider/core/node_modules/broccoli-persistent-filter/lib/index.js:83
async function invoke(context, fn, args) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dsolomon/Documents/learn-ember/super-rentals/node_modules/@embroider/core/src/template-compiler.js:15:54)
```

**Comment by cah-briangantzler** [comment]
Node 6 is pretty old. The current version says [Node >=10](https://github.com/miragejs/ember-cli-mirage/blob/master/package.json#L98). 

Looks like 1.1.8 removed node 6 [here](https://github.com/miragejs/ember-cli-mirage/blob/f89a3b9dbe7e926f9a801a5bfdc66b4cea02502f/package.json#L98)
